兼容 Windows 平台
keyou/chromium_demo pull request #37
Opened 2024-01-24 07:56 UTC by shaochenguang

1. 解决 Windows 编译错误。
2. demo_views 在 Windows 跑通。
3. demo_cc_gui 支持 M120

2024-01-24 08:16 UTC, keyou commented on BUILD.gn
> +    "demo_cc",
这几个在 mac 上验证了么？

2024-01-24 08:21 UTC, shaochenguang commented on BUILD.gn
> +    "demo_cc",
Mac 应该还不行，我修改一下

2024-01-25 03:42 UTC, shaochenguang commented on BUILD.gn
> +    "demo_cc",
Mac 上还有点问题，先屏蔽了这两个，后面支持。

2024-01-31 06:21 UTC, keyou requested changes

2024-01-31 06:21 UTC, keyou commented on BUILD.gn
> +      "demo_views",
这样只是在 mac 下排除了这两个 demo，但是 android 没有处理。建议每个平台支持的 demo 单独加到那个平台中，而不是默认加载 deps 中，然后在各个平台再减 `-` 掉。

2024-01-31 06:21 UTC, keyou commented on demo_views/demo_views.cc
> +    button->SetBounds(0, 0, 150, 50);
view 的大小为什么要改？

2024-01-31 10:35 UTC, shaochenguang commented on BUILD.gn
> +      "demo_views",
这里都是在 is_desktop 里面加的 mac 排除了，意思是 linux 也有可能有问题？

2024-01-31 10:35 UTC, shaochenguang commented on demo_views/demo_views.cc
> +    button->SetBounds(0, 0, 150, 50);
windows 这个view 盖住了按钮，调整一下位置

2024-02-07 02:34 UTC, keyou requested changes

2024-02-07 02:34 UTC, keyou commented on BUILD.gn
> +      "demo_views",
android 会有问题

2024-02-08 03:00 UTC, shaochenguang commented on BUILD.gn
> +      "demo_views",
这个修改了，只在 windows 和 linux 生效

2024-02-19 07:53 UTC, keyou approved these changes

2024-02-19 07:55 UTC, merged

2024-06-23 04:46 UTC, keyou commented
@allcontributors please add @shaochenguang  for code.